---

- hosts: all
  become: true
  pre_tasks:

  - name: update all servers
    tags: always
    package:
      update_cache: yes


- hosts: web_servers
  become: true
  tasks:

  - name: install apache pnd php
    tags: apache,apache2
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"  
      state: latest
      update_cache: yes
  
  - name: copy defult html file for site
    tags: apache,web,httpd
    copy:
      src: files/
      dest: /var/www/html/
      owner: root
      group: root
      mode: 0644



- hosts: db_servers
  become: true
  tasks:
  
  - name: install mariaDB package (AlmaLinux)
    tags: mariadb,db,almalinux
    dnf:
      name: mariedb
      state: latest
    when: ansible_distribution == "AlmaLinux"

  - name: install mariaDB package (Ubuntu)
    tags: mariadb,db,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest



